# docker-compose.yml
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: redis_poc
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d redis_poc"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: myuser
      DB_PASSWORD: mypass
      DB_NAME: redis_poc
      DB_HOST: db
      DB_PORT: 5432
      DB_SSLMODE: disable
      REDIS_ADDR: redis:6379
      REDIS_DB: 0
      SERVER_PORT: 8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped